### ISSUE TITLE
A question about how to use update_ensemble to set zookeeper membership list

### ISSUE THREAD

**Issue by ZichengMa** [kezhuw/zookeeper-client-rust#10]
Hi, Kezhu! Thank you for your contribution on this great library.
I posted this issue to ask how to use `update_ensemble` correctly since there is no document or examples about this function.
My goal is to modify the zookeeper membership list to the list I declared.
I have created a superuser su with password passwd. I tried the command  `reconfig -members server.1=localhost:2001:3001:participant;2181,server.2=localhost:2002:3002:participant;2182,server.3=localhost:2003:3003:participant;2183` directly in zkCli CLI and it worked. So I am wondering is there anything wrong about the usage of `EnsembleUpdate` struct or `update_ensemble` function?
Here is my code:
```rust
    let cluster = "localhost:2181";
    let client = zk::Client::connect(cluster, Duration::from_secs(20))
        .await
        .unwrap();

    let (config_bytes, stat, watcher) = client.get_and_watch_config().await.unwrap();

    println!(
        "config_contents: {:?}",
        String::from_utf8_lossy(&config_bytes)
    );
    client
        .auth("digest".to_string(), b"su:passwd".to_vec())
        .await
        .unwrap();

    let event = watcher.changed().await;
    assert_eq!(event.event_type, zk::EventType::NodeDataChanged);
    assert_eq!(event.path, "/zookeeper/config");

    let strings = vec![
        "server.1=localhost:2001:3001:participant;2181",
        "server.2=localhost:2002:3002:participant;2182",
        "server.3=localhost:2003:3003:participant;2183",
    ];
    let test_update = EnsembleUpdate::New {
        ensemble: strings.iter().cloned(),
    };
    let result = client.update_ensemble(test_update, Some(-1));
    result.await.unwrap();
``` 

The final result of this code is infinitely waiting, and no result comes out from the client.update_ensemble.

**Comment by kezhuw** [comment]
Hi @ZichengMa, thank you for your information!

I have solved this and verified locally. I plan to release a patch version today for this even though it is a breaking change in api. I will try to add a test for this in next feature release.

**Comment by kezhuw** [comment]
Hi @ZichengMa, `0.3.1` has been deployed to [crates.io](https://crates.io/crates/zookeeper-client/versions).

**Comment by kezhuw** [comment]
Just in case, `watcher.changed().await` in your code will block. You can move it after `update_ensemble`.
