### ISSUE TITLE
Support for emoji characters in path

### ISSUE THREAD

**Issue by Murphy-OrangeMud** [kezhuw/zookeeper-client-rust#13]
Hi,

It seems that the client sdk doesn't support emoji characters in path. For example, in `async fn example()` in `tests/zookeeper.rs`, when I modify `/abc/efg` to `/abc/中文.docx` the test will still pass, but when I modify it to `/abc/🐂🍺中文.docx` it will fail. I'm not sure if this is the restriction of zookeeper itself. I failed to search for relevant issues and only find this: 
https://stackoverflow.com/questions/55463167/node-name-limitations-in-zookeeper

And the unicode of the emojis are beyond FFFF. I'm not sure if it's a problem of encoding (like Vec<u8>)

**Comment by Xuanwo** [comment]
Is it a good idea to do url path encoding here?

**Comment by kezhuw** [comment]
Won't this be callers' responsibility to do whatever they want to do ? I think it is intrusive to do it in a ZooKeeper client library.

For the usage, I recommend either:
* Document as limitation.
* Encode every path segments from client and decode every path segments from server.

**Comment by Xuanwo** [comment]
Sorry for mixup the context: I'm talking about encode/decode at opendal side.

**Comment by kezhuw** [comment]
Closes as won't fix. It is also hard to support this in upstream as support this in newer version will break old clients.
