### ISSUE TITLE
Possible race condition in watchers

### ISSUE THREAD

**Issue by behos** [kezhuw/zookeeper-client-rust#22]
Hi,

I'm hitting a strange race condition when watching for data changes on nodes being deleted. It manifests as an unhandled error on a "NoWatchers" response from Zookeeper.

I am somehow hitting this condition without using persistent watches:
https://github.com/kezhuw/zookeeper-client-rust/blob/master/src/session/watch.rs#L362-L365

This sends a `RemoveWatches` request to Zookeeper, which fails with an error here, because the NoWatchers error is not handled:
https://github.com/kezhuw/zookeeper-client-rust/blob/master/src/session/mod.rs#L280-L298

I can't reproduce this issue in tests, but it happens in my service under fairly heavy load.

From some of my logs, it looks like the watchers are created, then dropped, then a notification is received from Zookeeper for those watches, finds that there are no watchers waiting and sends a `RemoveWatches` which fails.

A quick and dirty solution would be to and ignore the `NoWatchers` error, but I'm wondering if there's a way that we will lose valid notifications here, since I can't see how the watchers are dropped and we still get a notification back.

Edit:
This error comes through with a `0` header.xid so it can't be mapped to the `RemoveWatcher` request either.

**Comment by behos** [comment]
I was able to reproduce this with an example here https://github.com/DataDog/zookeeper-client-rust/blob/giorgos.georgiou/reproduce-remove-watch-issue/examples/lock_pressure.rs

```
RUST_LOG=debug cargo run --example lock_pressure
```

This can run for a while until logs of the failed operation start appearing:

```
[2024-02-02T08:43:08Z WARN  zookeeper_client::session::watch] removing dangling watcher
[2024-02-02T08:43:08Z DEBUG zookeeper_client::session::depot] ZooKeeper operation request: (RemoveWatches, Watch { path: "/lock0000295238", mode: Any })
...
[2024-02-02T08:43:08Z DEBUG zookeeper_client::session] ZooKeeper operation unknown failure: (RemoveWatches, Watch { path: "/lock0000295238", mode: Any }), UnexpectedErrorCode(-121)
```

**Comment by kezhuw** [comment]
Thank you for the report and reproduce example. @behos 

I am no sure I fully understand the problem you encountered. But I think there are probably several mixed conditions here:
1. Error code for `NoWatcher` should be `-121`. This cause an extra log and mismatch error response.
2. `xid` is not set in case of `RemoveWatches` is unblocked by `fail_watch`. This could cause session disconnected.
3. The race between [`OneshotWatcher::remove`](https://docs.rs/zookeeper-client/0.6.2/zookeeper_client/struct.OneshotWatcher.html#method.remove) and server-side oneshot event triggering. This is unavoidable due to the oneshot natural.

Base on  my understanding, I opened #24. Would you mind take a look if it sounds ?

**Comment by behos** [comment]
> Thank you for the report and reproduce example. @behos
> 
> I am no sure I fully understand the problem you encountered. But I think there are probably several mixed conditions here:
> 
> 1. Error code for `NoWatcher` should be `-121`. This cause an extra log and mismatch error response.
> 2. `xid` is not set in case of `RemoveWatches` is unblocked by `fail_watch`. This could cause session disconnected.
> 3. The race between [`OneshotWatcher::remove`](https://docs.rs/zookeeper-client/0.6.2/zookeeper_client/struct.OneshotWatcher.html#method.remove) and server-side oneshot event triggering. This is unavoidable due to the oneshot natural.
> 
> Base on my understanding, I opened #24. Would you mind take a look if it sounds ?

Sorry, I missed this notification. With #24 merged, I'll check it with my breaking example again and close the other PR. It looks like it addresses the issues I identified

**Comment by behos** [comment]
@kezhuw I can verify that the issue I was seeing is not happening in 0.6.3! Thanks for the fix :)

**Comment by kezhuw** [comment]
@behos Glad to hear! Thank you for verification!
